# Generated by Django 4.2.5 on 2023-09-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_creation_date_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='reply',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
