# Generated by Django 4.2.5 on 2023-09-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_creation_date_reply_is_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingMailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_send_date', models.DateTimeField()),
            ],
        ),
    ]
